---
- name: Create a directory for compose project
  ansible.builtin.file:
    path: "/opt/services"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy of compose file to server
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/opt/services/{{ item }}"
    mode: '0755'
    owner: root
    group: root
  loop:
    - proxy_manager.yaml
    - wikijs.yaml
    - cmdbuild.yaml
    - vcenter.yaml
