services:

  proxy_manager:
    image: jc21/nginx-proxy-manager:2.11.3
    container_name: proxy_manager
    restart: always
    network_mode: host
    expose:
      - "80"
      - "81"
      - "443"
    volumes:
      - proxy_manager/app:/data
      - proxy_manager/letsencrypt:/etc/letsencrypt

volumes:
  proxy_manager:
    name: proxy_manager
