---
- name: Update packages
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Reboot server
  ansible.builtin.reboot:
    reboot_timeout: 3600

- name: Install program packages
  ansible.builtin.apt:
    name:
      - fail2ban
      - nginx
      - nmap
    state: present
