---
- name: Setup ssh service
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Restart ssh service
  ansible.builtin.systemd_service:
    name: ssh.service
    state: restarted
    enabled: true
