---
- name: Install docker
  ansible.builtin.shell:
    cmd: curl -fsSL https://get.docker.com | sh

- name: Start docker
  ansible.builtin.systemd_service:
    name: docker.service
    state: started
    enabled: true
