---
- name: Update cache
  ansible.builtin.dnf:
    update_cache: true

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install program packages
  ansible.builtin.dnf:
    name:
      - epel-release
      - nmap
    state: present

- name: Reboot server
  ansible.builtin.reboot:
    reboot_timeout: 3600
