---
- name: Update cache
  ansible.builtin.dnf:
    update_cache: true

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Reboot server
  ansible.builtin.reboot:
    reboot_timeout: 3600

- name: Install a package of epel-release
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Install a packages
  ansible.builtin.dnf:
    name:
      - fail2ban
      - nginx
      - nmap
    state: present
