- name: Install a package of fail2ban
  ansible.builtin.dnf:
    name: fail2ban
    state: present

- name: Copy of fail2ban config to server
  ansible.builtin.copy:
    src: "files/sshd.conf"
    dest: "/etc/fail2ban/jail.d/sshd.conf"
    mode: '0755'
    owner: root
    group: root

- name: Restart fail2ban service
  ansible.builtin.systemd_service:
    name: fail2ban.service
    state: restarted
    enabled: true
