---
- name: Delete cockpit service rule
  ansible.posix.firewalld:
    zone: public
    service: cockpit
    permanent: true
    state: disabled

- name: Delete dhcpv6-client service rule
  ansible.posix.firewalld:
    zone: public
    service: dhcpv6-client
    permanent: true
    state: disabled

- name: Delete ssh service rule
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: true
    state: disabled

- name: Enable ssh port
  ansible.posix.firewalld:
    zone: public
    port: 22/tcp
    permanent: true
    state: enabled

- name: Restart firewalld service
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: restarted
    enabled: true
