---
- name: Import tasks from dnf.yaml
  ansible.builtin.import_tasks: dnf.yaml

- name: Import tasks from firewalld.yaml
  ansible.builtin.import_tasks: firewalld.yaml

- name: Import tasks from ssh.yaml
  ansible.builtin.import_tasks: ssh.yaml

- name: Import tasks from fail2ban.yaml
  ansible.builtin.import_tasks: fail2ban.yaml

- name: Import tasks from docker.yaml
  ansible.builtin.import_tasks: docker.yaml
