---
- name: Delete cockpit service rule
  ansible.posix.firewalld:
    zone: public
    service: cockpit
    permanent: true
    state: absent

- name: Delete dhcpv6-client service rule
  ansible.posix.firewalld:
    zone: public
    service: dhcpv6-client
    permanent: true
    state: absent

- name: Restart firewalld service
  ansible.builtin.systemd_service:
    name: firewalld.service
    state: restarted
    enabled: true
