---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Start ufw service
  ansible.builtin.systemd_service:
    name: ufw.service
    state: started
    enabled: true

- name: Reset ufw
  community.general.ufw:
    state: reset

- name: Set default policies to deny incoming
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set default policies to allow outgoing
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '22'
