---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Start ufw service
  ansible.builtin.systemd_service:
    name: ufw
    state: started
    enabled: true

- name: Reset ufw
  community.general.ufw:
    state: reset

- name: Common setup ufw
  ansible.builtin.shell:
    cmd: |
      ufw default deny incoming
      ufw default allow outgoing
      ufw allow 22

- name: Enable ufw
  community.general.ufw:
    state: enabled
